name: community_parade
description: A community parade project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database:
    git:
      url: https://github.com/jpeiffer/flutterfire
      path: packages/firebase_database
      ref: 2d336caeb9ea65fcaaf83035e1653415f7017ae6
  flutter_map: ^0.9.0
  provider: ^4.0.5
  rest_client: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
