name: community_parade
description: A community parade project
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  encrypt: ^4.0.0
  firebase: ^7.3.0
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.5
  flutter_map: ^0.9.0
  flutter_secure_storage: ^3.3.3
  geolocator: ^5.3.1
  logging: ^0.11.4
  pointycastle: ^1.0.1
  provider: ^4.0.5
  rest_client: any
  sembast: ^2.4.3
  sembast_web: ^1.1.0
  websafe_network_image: any
  websafe_platform: any
  websafe_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets-src/icon_transparent.png"
  image_path: "assets-src/icon_white.png"


flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/secure/
